/**
 * SUIKA X — Companion Intelligence Layer.
 *
 * This module is the "always-on companion" that observes every conversation,
 * maintains a structured understanding of the user's projects and goals,
 * evolves its own personality from experience, and proactively proposes
 * initiatives. It is the bridge between the reactive Agent Runtime (which
 * executes dispatched tasks) and the proactive user-partner layer.
 *
 * Six subsystems live here:
 *
 *   1. Context Fusion Engine       — fuseContext()
 *      Composes a FusedContext from a user message by simultaneously
 *      querying projects, goals, memories, workflows, knowledge entities,
 *      user facts, recent decisions, open blockers, and open threads.
 *      Returns a natural-language digest plus structured IDs.
 *
 *   2. Project Manager             — listProjects, getProject, createProject,
 *                                     updateProjectProgress, addMilestone,
 *                                     addTask, addDecision, addBlocker,
 *                                     resolveBlocker, detectProjectFromMessage
 *      Autonomous project tracking: milestones, tasks, decisions, blockers.
 *      Each ProjectDTO carries aggregated progress metrics.
 *
 *   3. Conversation Analysis       — analyzeConversation, persistConversationAnalysis
 *      LLM-extracts summary / topics / decisions / action items / facts /
 *      sentiment / project mentions / next actions. Falls back to heuristic
 *      extraction on LLM or JSON-parse failure. Persists a ConversationSummary,
 *      dedups and persists UserFacts, updates RelationshipState, optionally
 *      bumps project progress, and emits an event.
 *
 *   4. Personality Engine          — getActiveTraits, evolveTraits
 *      Maintains a versioned CompanionTraits row. Each evolveTraits() call
 *      applies small deltas based on success/failure/reflection/sentiment,
 *      clamps to [0.1, 1.0], deactivates the old row, and creates a new
 *      versioned row (immutable history).
 *
 *   5. Initiative Engine           — generateInitiatives, listInitiatives,
 *                                     decideInitiative, executeInitiative
 *      Gathers signals (active goals, open blockers, dead-lettered jobs,
 *      failed tasks, open threads), asks the LLM for initiative suggestions,
 *      falls back to heuristics on failure, persists InitiativeAction rows
 *      with 24h expiry, and can execute accepted initiatives by enqueuing a
 *      durable job through the existing job-queue.
 *
 *   6. Companion State Aggregator  — getCompanionState
 *      Single-call snapshot of the companion's view of the user: profile,
 *      traits, relationship, projects, initiatives, recent decisions, and
 *      fresh suggested actions.
 *
 * Design notes:
 *   - All functions are async and awaitable.
 *   - LLM calls are wrapped in try/catch with graceful heuristic fallbacks.
 *   - JSON-string DB columns are parsed via readJSON() with safe defaults.
 *   - JSON-string DB columns are written via writeJSON() (never null).
 *   - IDs are cuid() auto-generated by Prisma — we never pass `id` in create data.
 *   - Prisma types (Project, ProjectMilestone, etc.) are imported from
 *     @prisma/client; DTO types are defined locally.
 */
import ZAI from "z-ai-web-dev-sdk";
import type {
  Project,
  ProjectMilestone,
  ProjectTask,
  ProjectDecision,
  ProjectBlocker,
  InitiativeAction,
  UserFact,
  CompanionTraits,
} from "@prisma/client";

import { db } from "@/lib/db";
import { emit } from "@/lib/suika/kernel";
import { readJSON, writeJSON } from "@/lib/suika/json";
import { enqueue } from "@/lib/suika/job-queue";
import type {
  AgentContext,
  TaskKind,
} from "@/lib/suika/types";

// ─── Constants ───────────────────────────────────────────────────────────────

const DEFAULT_PROFILE_ID = "default";
const DEFAULT_WORKSPACE_ID = "default";

const STOP_WORDS = new Set<string>([
  "the","a","an","is","are","was","were","be","been","being","am","have","has",
  "had","do","does","did","doing","will","would","could","should","may","might",
  "must","shall","can","need","dare","ought","used","to","of","in","for","on",
  "with","at","by","from","as","into","through","during","before","after",
  "above","below","between","under","again","further","then","once","here",
  "there","when","where","why","how","all","any","both","each","few","more",
  "most","other","some","such","no","nor","not","only","own","same","so","than",
  "too","very","just","but","and","or","if","while","about","i","you","he","she",
  "it","we","they","me","him","her","us","them","my","your","his","its","our",
  "their","this","that","these","those","what","which","who","whom","whose",
  "myself","yourself","himself","herself","itself","ourselves","themselves",
  "want","wanna","gonna","yeah","ok","okay","please","thanks","thank","hi",
  "hello","hey","like","get","got","let","lets","u","ur","r","k","kk",
]);

// ─── Public DTOs ─────────────────────────────────────────────────────────────

export interface FusedContext {
  userMessage: string;
  detectedTopics: string[];
  detectedProjectIds: string[];
  detectedGoalIds: string[];
  detectedMemoryIds: string[];
  detectedWorkflowIds: string[];
  detectedKnowledgeNodeIds: string[];
  relevantFacts: UserFact[];
  recentDecisions: ProjectDecision[];
  activeBlockers: ProjectBlocker[];
  openThreads: string[];
  summary: string;
}

export interface ProjectDTO {
  id: string;
  name: string;
  description: string;
  status: string;
  priority: number;
  progress: number;
  category: string;
  milestones: { total: number; achieved: number; inProgress: number };
  tasks: { total: number; done: number; inProgress: number; blocked: number };
  openBlockers: number;
  recentDecisions: number;
  createdAt: string;
  updatedAt: string;
}

export interface ConversationAnalysis {
  summary: string;
  topics: string[];
  decisions: string[];
  actionItems: string[];
  facts: Array<{ kind: string; content: string; confidence: number }>;
  sentiment: "positive" | "neutral" | "negative" | "mixed";
  projectMentions: string[];
  nextActions: string[];
}

export interface CompanionTraitsDTO {
  curiosity: number;
  confidence: number;
  focus: number;
  creativity: number;
  empathy: number;
  persistence: number;
  version: number;
  rationale: string;
}

export interface InitiativeSuggestion {
  id?: string;
  kind: "suggestion" | "autonomous_workflow" | "research_task" | "reminder";
  title: string;
  description: string;
  rationale: string;
  priority: number;
  sourceSignals: Record<string, unknown>;
  linkedProjectId?: string;
  linkedGoalId?: string;
}

export interface CompanionState {
  profile: { name: string; preferredName: string; expertiseLevel: string };
  traits: CompanionTraitsDTO;
  relationship: {
    trustLevel: number;
    rapportLevel: number;
    engagementTrend: string;
    totalInteractions: number;
    openThreadsCount: number;
  };
  projects: { active: number; totalProgress: number; openBlockers: number };
  initiatives: { proposed: number; accepted: number; executed: number };
  recentDecisions: ProjectDecision[];
  suggestedActions: InitiativeSuggestion[];
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Tokenize a message into lowercase keyword tokens (strip punctuation, drop
 *  stopwords, drop 2-char noise). */
function tokenize(message: string): string[] {
  const raw = message
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .map((t) => t.trim())
    .filter((t) => t.length > 2 && !STOP_WORDS.has(t));
  // dedupe preserving order
  return Array.from(new Set(raw));
}

function clamp(n: number, min: number, max: number): number {
  if (n < min) return min;
  if (n > max) return max;
  return n;
}

function clamp01(n: number): number {
  return clamp(n, 0.1, 1.0);
}

/** Round to N decimals to keep DB-stored floats clean. */
function round(n: number, decimals = 4): number {
  const f = Math.pow(10, decimals);
  return Math.round(n * f) / f;
}

/** Strip markdown code fences and leading/trailing noise, then JSON.parse. */
function parseLLMJson<T>(text: string): T | null {
  if (!text) return null;
  let s = text.trim();
  // Strip ```json ... ``` or ``` ... ``` fences
  s = s.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/i, "");
  // If there's still surrounding prose, extract the outermost JSON value.
  const firstBrace = s.search(/[\[{]/);
  const lastBrace = Math.max(s.lastIndexOf("}"), s.lastIndexOf("]"));
  if (firstBrace >= 0 && lastBrace > firstBrace) {
    s = s.slice(firstBrace, lastBrace + 1);
  }
  try {
    return JSON.parse(s) as T;
  } catch {
    return null;
  }
}

/** Direct LLM call wrapper. Returns the assistant text, or "" on failure. */
async function callLLM(systemPrompt: string, userPrompt: string): Promise<string> {
  try {
    const zai = await ZAI.create();
    const completion = await zai.chat.completions.create({
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      thinking: { type: "disabled" },
    });
    return completion.choices[0]?.message?.content ?? "";
  } catch (e) {
    const msg = (e as Error)?.message ?? String(e);
    await emit("warn", "companion", "LLM call failed; using fallback", {
      error: msg.slice(0, 200),
    });
    return "";
  }
}

/** Assemble a minimal AgentContext for companion-initiated workflows. The
 *  companion is part of SUIKA itself, so its initiatives are pre-cleared by
 *  the constitution gate (synthetic "compliant" verdict). */
function companionAgentContext(initiative: {
  kind: string;
  title: string;
  description?: string;
}): AgentContext {
  return {
    constitution: {
      verdict: "compliant",
      severity: "info",
      evaluationId: "companion-initiative",
      summary: `Companion-initiated ${initiative.kind}: ${initiative.title}`,
    },
    identity: null,
    relationship: null,
    goals: [],
    projects: [],
    memories: [],
    summary: `Companion initiative: ${initiative.title}. ${initiative.description ?? ""}`,
  };
}

/**
 * Resolve an input `profileId` (e.g. "default", a RelationshipProfile.id) to
 * the cuid of the corresponding UserProfile row. The Phase 4.3 tables
 * (UserFact, UserPreference, ConversationSummary, RelationshipState) all FK
 * to UserProfile.id, NOT to the input profileId string — so every read/write
 * on those tables must use this resolved id.
 *
 * Find-or-create: if no UserProfile exists for the given profileId, an empty
 * one is seeded. This is safe because the companion layer is the primary
 * writer of UserProfile rows.
 */
async function resolveUserProfileId(profileId: string): Promise<string> {
  const existing = await db.userProfile.findUnique({
    where: { profileId },
    select: { id: true },
  });
  if (existing) return existing.id;
  const created = await db.userProfile.create({
    data: { profileId },
  });
  await emit("info", "companion", "UserProfile auto-created", { profileId });
  return created.id;
}

/** Look up the UserProfile.id for a profileId without creating one. Returns
 *  null if no UserProfile exists yet (read-only paths use this to avoid
 *  surprising side effects). */
async function findUserProfileId(profileId: string): Promise<string | null> {
  const row = await db.userProfile.findUnique({
    where: { profileId },
    select: { id: true },
  });
  return row?.id ?? null;
}

// ─── 1. Context Fusion Engine ────────────────────────────────────────────────

export async function fuseContext(opts: {
  userMessage: string;
  profileId?: string;
  workspaceId?: string;
  limit?: number;
}): Promise<FusedContext> {
  const profileId = opts.profileId ?? DEFAULT_PROFILE_ID;
  const workspaceId = opts.workspaceId ?? DEFAULT_WORKSPACE_ID;
  const limit = Math.max(1, Math.min(opts.limit ?? 5, 20));
  const userMessage = opts.userMessage ?? "";

  const keywords = tokenize(userMessage);
  const detectedTopics = keywords.slice(0, 10);

  const lowerMsg = userMessage.toLowerCase();

  // ── Projects: substring match on name (case-insensitive) ─────────────────
  const allProjects = await db.project.findMany({
    where: { profileId },
    select: { id: true, name: true },
    take: 200,
  });
  const detectedProjectIds = allProjects
    .filter((p) => p.name && lowerMsg.includes(p.name.toLowerCase()))
    .map((p) => p.id);

  // ── Goals: substring match on title ──────────────────────────────────────
  const allGoals = await db.relationshipGoal.findMany({
    where: { profileId },
    select: { id: true, title: true },
    take: 200,
  });
  const detectedGoalIds = allGoals
    .filter((g) => g.title && lowerMsg.includes(g.title.toLowerCase()))
    .map((g) => g.id);

  // ── Memories: contains-any-keyword (top 5 by recency) ────────────────────
  let detectedMemoryIds: string[] = [];
  let memorySnippets: string[] = [];
  if (keywords.length > 0) {
    const memories = await db.memory.findMany({
      where: {
        workspaceId,
        OR: keywords.slice(0, 8).map((kw) => ({ content: { contains: kw } })),
      },
      select: { id: true, content: true },
      orderBy: { createdAt: "desc" },
      take: limit,
    });
    detectedMemoryIds = memories.map((m) => m.id);
    memorySnippets = memories.map((m) =>
      m.content.length > 80 ? m.content.slice(0, 80) + "…" : m.content
    );
  }

  // ── Workflows (executionJobs): contains-any-keyword, top 3 recent ────────
  let detectedWorkflowIds: string[] = [];
  if (keywords.length > 0) {
    const jobs = await db.executionJob.findMany({
      where: {
        OR: keywords.slice(0, 8).map((kw) => ({ title: { contains: kw } })),
      },
      select: { id: true },
      orderBy: { createdAt: "desc" },
      take: 3,
    });
    detectedWorkflowIds = jobs.map((j) => j.id);
  }

  // ── Knowledge fabric entities: name contains keyword ─────────────────────
  let detectedKnowledgeNodeIds: string[] = [];
  if (keywords.length > 0) {
    const entities = await db.entity.findMany({
      where: {
        OR: keywords.slice(0, 8).map((kw) => ({ name: { contains: kw } })),
      },
      select: { id: true },
      take: limit,
    });
    detectedKnowledgeNodeIds = entities.map((e) => e.id);
  }

  // ── User facts: contains-any-keyword (Phase 4.3 tables FK to UserProfile.id) ──
  let relevantFacts: UserFact[] = [];
  const userProfileId = await findUserProfileId(profileId);
  if (keywords.length > 0 && userProfileId) {
    relevantFacts = await db.userFact.findMany({
      where: {
        profileId: userProfileId,
        OR: keywords.slice(0, 8).map((kw) => ({ content: { contains: kw } })),
      },
      take: limit,
      orderBy: { extractedAt: "desc" },
    });
  }

  // ── Recent project decisions: title/context contains keyword ─────────────
  let recentDecisions: ProjectDecision[] = [];
  if (keywords.length > 0) {
    recentDecisions = await db.projectDecision.findMany({
      where: {
        OR: keywords.slice(0, 6).flatMap((kw) => [
          { title: { contains: kw } },
          { context: { contains: kw } },
        ]),
      },
      orderBy: { decidedAt: "desc" },
      take: 3,
    });
  }

  // ── Active blockers: status=open + keyword match ─────────────────────────
  let activeBlockers: ProjectBlocker[] = [];
  if (keywords.length > 0) {
    activeBlockers = await db.projectBlocker.findMany({
      where: {
        status: "open",
        OR: keywords.slice(0, 6).flatMap((kw) => [
          { title: { contains: kw } },
          { description: { contains: kw } },
        ]),
      },
      orderBy: { identifiedAt: "desc" },
      take: 3,
    });
  }

  // ── Open threads from RelationshipState (FK to UserProfile.id) ──────────
  const relState = userProfileId
    ? await db.relationshipState.findUnique({
        where: { profileId: userProfileId },
        select: { openThreads: true },
      })
    : null;
  const openThreads = readJSON<string[]>(relState?.openThreads ?? "[]", []);

  // ── Natural-language summary ──────────────────────────────────────────────
  const summaryParts: string[] = [];
  if (detectedTopics.length > 0) {
    summaryParts.push(`User is discussing ${detectedTopics.slice(0, 5).join(", ")}.`);
  }
  if (detectedProjectIds.length > 0) {
    const names = allProjects
      .filter((p) => detectedProjectIds.includes(p.id))
      .map((p) => p.name);
    summaryParts.push(`Relevant projects: ${names.join(", ")}.`);
  }
  if (activeBlockers.length > 0) {
    summaryParts.push(
      `Active blockers: ${activeBlockers.map((b) => b.title).join("; ")}.`
    );
  }
  if (memorySnippets.length > 0) {
    summaryParts.push(`Relevant memories: ${memorySnippets.join(" | ")}.`);
  }
  if (relevantFacts.length > 0) {
    summaryParts.push(
      `Known facts: ${relevantFacts.map((f) => f.content.slice(0, 60)).join("; ")}.`
    );
  }
  if (openThreads.length > 0) {
    summaryParts.push(`Open threads: ${openThreads.slice(0, 3).join("; ")}.`);
  }
  const summary =
    summaryParts.length > 0
      ? summaryParts.join(" ")
      : "No specific context detected from the message.";

  return {
    userMessage,
    detectedTopics,
    detectedProjectIds,
    detectedGoalIds,
    detectedMemoryIds,
    detectedWorkflowIds,
    detectedKnowledgeNodeIds,
    relevantFacts,
    recentDecisions,
    activeBlockers,
    openThreads,
    summary,
  };
}

// ─── 2. Project Manager ──────────────────────────────────────────────────────

/** Build a ProjectDTO from a Prisma Project row + pre-fetched related rows. */
function toProjectDTO(
  project: Project,
  milestones: ProjectMilestone[],
  tasks: ProjectTask[],
  blockers: ProjectBlocker[],
  decisions: ProjectDecision[]
): ProjectDTO {
  return {
    id: project.id,
    name: project.name,
    description: project.description,
    status: project.status,
    priority: project.priority,
    progress: project.progress,
    category: project.category,
    milestones: {
      total: milestones.length,
      achieved: milestones.filter((m) => m.status === "achieved").length,
      inProgress: milestones.filter((m) => m.status === "in_progress").length,
    },
    tasks: {
      total: tasks.length,
      done: tasks.filter((t) => t.status === "done").length,
      inProgress: tasks.filter((t) => t.status === "in_progress").length,
      blocked: tasks.filter((t) => t.status === "blocked").length,
    },
    openBlockers: blockers.filter((b) => b.status === "open").length,
    recentDecisions: decisions.length,
    createdAt: project.createdAt.toISOString(),
    updatedAt: project.updatedAt.toISOString(),
  };
}

export async function listProjects(opts: {
  profileId?: string;
  includeArchived?: boolean;
}): Promise<ProjectDTO[]> {
  const profileId = opts.profileId ?? DEFAULT_PROFILE_ID;
  const where: { profileId: string; status?: { not: string } } = { profileId };
  if (!opts.includeArchived) {
    where.status = { not: "archived" };
  }

  const projects = await db.project.findMany({
    where,
    orderBy: [{ status: "asc" }, { updatedAt: "desc" }],
    take: 200,
  });
  if (projects.length === 0) return [];

  const ids = projects.map((p) => p.id);
  const [milestones, tasks, blockers, decisions] = await Promise.all([
    db.projectMilestone.findMany({ where: { projectId: { in: ids } } }),
    db.projectTask.findMany({ where: { projectId: { in: ids } } }),
    db.projectBlocker.findMany({ where: { projectId: { in: ids } } }),
    db.projectDecision.findMany({
      where: { projectId: { in: ids } },
      orderBy: { decidedAt: "desc" },
      take: 10,
    }),
  ]);

  return projects.map((p) =>
    toProjectDTO(
      p,
      milestones.filter((m) => m.projectId === p.id),
      tasks.filter((t) => t.projectId === p.id),
      blockers.filter((b) => b.projectId === p.id),
      decisions.filter((d) => d.projectId === p.id)
    )
  );
}

export async function getProject(id: string): Promise<ProjectDTO | null> {
  const project = await db.project.findUnique({ where: { id } });
  if (!project) return null;

  const [milestones, tasks, blockers, decisions] = await Promise.all([
    db.projectMilestone.findMany({ where: { projectId: id } }),
    db.projectTask.findMany({ where: { projectId: id } }),
    db.projectBlocker.findMany({ where: { projectId: id } }),
    db.projectDecision.findMany({
      where: { projectId: id },
      orderBy: { decidedAt: "desc" },
      take: 10,
    }),
  ]);

  return toProjectDTO(project, milestones, tasks, blockers, decisions);
}

export async function createProject(input: {
  name: string;
  description?: string;
  category?: string;
  priority?: number;
  profileId?: string;
  targetDate?: Date;
}): Promise<Project> {
  const project = await db.project.create({
    data: {
      profileId: input.profileId ?? DEFAULT_PROFILE_ID,
      name: input.name,
      description: input.description ?? "",
      category: input.category ?? "general",
      priority: clamp(Math.round(input.priority ?? 50), 0, 100),
      targetDate: input.targetDate ?? null,
    },
  });
  await emit("info", "project", `Project created: ${input.name}`, {
    projectId: project.id,
    category: project.category,
  });
  return project;
}

export async function updateProjectProgress(
  id: string,
  progress: number
): Promise<void> {
  const clamped = clamp(Math.round(progress), 0, 100);
  const data: { progress: number; status?: string; completedAt?: Date } = { progress: clamped };
  if (clamped >= 100) {
    data.status = "completed";
    data.completedAt = new Date();
  }
  await db.project.update({ where: { id }, data });
  await emit("debug", "project", `Project progress updated`, {
    projectId: id,
    progress: clamped,
  });
}

export async function addMilestone(input: {
  projectId: string;
  title: string;
  description?: string;
  targetDate?: Date;
  significance?: number;
}): Promise<ProjectMilestone> {
  // Append after existing milestones to preserve order.
  const existing = await db.projectMilestone.count({
    where: { projectId: input.projectId },
  });
  const milestone = await db.projectMilestone.create({
    data: {
      projectId: input.projectId,
      title: input.title,
      description: input.description ?? "",
      targetDate: input.targetDate ?? null,
      significance: clamp(Math.round(input.significance ?? 50), 0, 100),
      order: existing,
    },
  });
  await emit("info", "project", `Milestone added: ${input.title}`, {
    projectId: input.projectId,
    milestoneId: milestone.id,
  });
  return milestone;
}

export async function addTask(input: {
  projectId: string;
  title: string;
  description?: string;
  priority?: number;
  dueDate?: Date;
}): Promise<ProjectTask> {
  const task = await db.projectTask.create({
    data: {
      projectId: input.projectId,
      title: input.title,
      description: input.description ?? "",
      priority: clamp(Math.round(input.priority ?? 50), 0, 100),
      dueDate: input.dueDate ?? null,
    },
  });
  await emit("info", "project", `Task added: ${input.title}`, {
    projectId: input.projectId,
    taskId: task.id,
  });
  return task;
}

export async function addDecision(input: {
  projectId: string;
  title: string;
  context?: string;
  options?: string[];
  chosen?: string;
  rationale?: string;
}): Promise<ProjectDecision> {
  const decision = await db.projectDecision.create({
    data: {
      projectId: input.projectId,
      title: input.title,
      context: input.context ?? "",
      options: writeJSON(input.options ?? []),
      chosen: input.chosen ?? "",
      rationale: input.rationale ?? "",
      decidedAt: new Date(),
    },
  });
  await emit("info", "project", `Decision recorded: ${input.title}`, {
    projectId: input.projectId,
    decisionId: decision.id,
  });
  return decision;
}

export async function addBlocker(input: {
  projectId: string;
  title: string;
  description?: string;
  severity?: string;
  proposedMitigation?: string;
}): Promise<ProjectBlocker> {
  const blocker = await db.projectBlocker.create({
    data: {
      projectId: input.projectId,
      title: input.title,
      description: input.description ?? "",
      severity: input.severity ?? "medium",
      status: "open",
      proposedMitigation: input.proposedMitigation ?? "",
    },
  });
  await emit("warn", "project", `Blocker identified: ${input.title}`, {
    projectId: input.projectId,
    blockerId: blocker.id,
    severity: blocker.severity,
  });
  return blocker;
}

export async function resolveBlocker(id: string): Promise<void> {
  await db.projectBlocker.update({
    where: { id },
    data: { status: "resolved", resolvedAt: new Date() },
  });
  await emit("info", "project", `Blocker resolved`, { blockerId: id });
}

export async function detectProjectFromMessage(
  message: string,
  profileId?: string
): Promise<Project | null> {
  const lower = message.toLowerCase();
  const projects = await db.project.findMany({
    where: { profileId: profileId ?? DEFAULT_PROFILE_ID },
    take: 200,
  });
  // Prefer the longest-name match (most specific), tiebreak by priority desc.
  const matches = projects.filter((p) => p.name && lower.includes(p.name.toLowerCase()));
  if (matches.length === 0) return null;
  matches.sort((a, b) => {
    if (b.name.length !== a.name.length) return b.name.length - a.name.length;
    return b.priority - a.priority;
  });
  return matches[0];
}

// ─── 3. Conversation Analysis + Fact Extraction ────────────────────────────

const CONVERSATION_ANALYSIS_SYSTEM_PROMPT = `You are SUIKA's conversation analyzer. Read the conversation and produce a STRICT JSON object describing it. Output ONLY the JSON — no markdown fences, no commentary.

JSON schema (fill every field, use empty arrays when nothing applies):
{
  "summary": "1-2 sentence summary of the conversation",
  "topics": ["topic1", "topic2"],
  "decisions": ["decision that was made", "..."],
  "actionItems": ["concrete next action", "..."],
  "facts": [
    {"kind": "personal|professional|technical|preference|goal", "content": "fact about the user", "confidence": 0.0-1.0}
  ],
  "sentiment": "positive|neutral|negative|mixed",
  "projectMentions": ["project name as spoken by user", "..."],
  "nextActions": ["follow-up SUIKA could take", "..."]
}

Rules:
- Extract facts ONLY about the user (not about SUIKA).
- Confidence is a number 0..1.
- sentiment is one of the 4 enum values.
- Project mentions are names of projects the user referenced (verbatim if possible).`;

export async function analyzeConversation(opts: {
  messages: Array<{ role: "user" | "assistant"; content: string }>;
  profileId?: string;
}): Promise<ConversationAnalysis> {
  const profileId = opts.profileId ?? DEFAULT_PROFILE_ID;
  const messages = opts.messages ?? [];

  if (messages.length === 0) {
    return emptyAnalysis();
  }

  const transcript = messages
    .map((m) => `${m.role.toUpperCase()}: ${m.content}`)
    .join("\n\n");

  const raw = await callLLM(
    CONVERSATION_ANALYSIS_SYSTEM_PROMPT,
    `Analyze this conversation:\n\n${transcript.slice(0, 8000)}`
  );

  const parsed = parseLLMJson<Partial<ConversationAnalysis>>(raw);
  if (parsed && typeof parsed === "object" && parsed.summary) {
    return normalizeAnalysis(parsed);
  }

  // ── Heuristic fallback ────────────────────────────────────────────────────
  return heuristicAnalysis(messages, profileId);
}

function emptyAnalysis(): ConversationAnalysis {
  return {
    summary: "",
    topics: [],
    decisions: [],
    actionItems: [],
    facts: [],
    sentiment: "neutral",
    projectMentions: [],
    nextActions: [],
  };
}

function normalizeAnalysis(p: Partial<ConversationAnalysis>): ConversationAnalysis {
  const sentiment = (p.sentiment as ConversationAnalysis["sentiment"]) ?? "neutral";
  return {
    summary: typeof p.summary === "string" ? p.summary.slice(0, 1000) : "",
    topics: Array.isArray(p.topics) ? p.topics.filter((t) => typeof t === "string").slice(0, 20) : [],
    decisions: Array.isArray(p.decisions) ? p.decisions.filter((t) => typeof t === "string").slice(0, 20) : [],
    actionItems: Array.isArray(p.actionItems) ? p.actionItems.filter((t) => typeof t === "string").slice(0, 20) : [],
    facts: Array.isArray(p.facts)
      ? p.facts
          .filter((f) => f && typeof f.content === "string")
          .slice(0, 20)
          .map((f) => ({
            kind: typeof f.kind === "string" ? f.kind : "personal",
            content: String(f.content).slice(0, 500),
            confidence: typeof f.confidence === "number" ? clamp(f.confidence, 0, 1) : 0.6,
          }))
      : [],
    sentiment: ["positive", "neutral", "negative", "mixed"].includes(sentiment)
      ? sentiment
      : "neutral",
    projectMentions: Array.isArray(p.projectMentions)
      ? p.projectMentions.filter((t) => typeof t === "string").slice(0, 10)
      : [],
    nextActions: Array.isArray(p.nextActions) ? p.nextActions.filter((t) => typeof t === "string").slice(0, 20) : [],
  };
}

function heuristicAnalysis(
  messages: Array<{ role: "user" | "assistant"; content: string }>,
  _profileId: string
): ConversationAnalysis {
  const userMsgs = messages.filter((m) => m.role === "user").map((m) => m.content);
  const lastUser = userMsgs[userMsgs.length - 1] ?? "";
  const allText = messages.map((m) => m.content).join(" ");
  const tokens = tokenize(allText);
  return {
    summary: lastUser.slice(0, 200) || "(no user message)",
    topics: tokens.slice(0, 5),
    decisions: [],
    actionItems: [],
    facts: [],
    sentiment: "neutral",
    projectMentions: [],
    nextActions: [],
  };
}

export async function persistConversationAnalysis(opts: {
  analysis: ConversationAnalysis;
  profileId?: string;
  channel?: "text" | "voice";
  messageCount: number;
  startedAt: Date;
  endedAt?: Date;
}): Promise<{ summaryId: string; factIds: string[] }> {
  const profileId = opts.profileId ?? DEFAULT_PROFILE_ID;
  const channel = opts.channel ?? "text";
  const analysis = opts.analysis;

  // Phase 4.3 tables (ConversationSummary, UserFact, RelationshipState) FK to
  // UserProfile.id (cuid), not to the input profileId string. Resolve it once.
  const userProfileId = await resolveUserProfileId(profileId);

  // 1. Create ConversationSummary row
  const summary = await db.conversationSummary.create({
    data: {
      profileId: userProfileId,
      channel,
      summary: analysis.summary,
      topics: writeJSON(analysis.topics),
      decisions: writeJSON(analysis.decisions),
      actionItems: writeJSON(analysis.actionItems),
      sentiment: analysis.sentiment,
      startedAt: opts.startedAt,
      endedAt: opts.endedAt ?? new Date(),
      messageCount: opts.messageCount,
    },
  });

  // 2. Create UserFact rows (dedup by content for this profile)
  const factIds: string[] = [];
  for (const fact of analysis.facts) {
    const existing = await db.userFact.findFirst({
      where: { profileId: userProfileId, content: fact.content },
      select: { id: true },
    });
    if (existing) {
      factIds.push(existing.id);
      continue;
    }
    const created = await db.userFact.create({
      data: {
        profileId: userProfileId,
        kind: fact.kind,
        content: fact.content,
        confidence: fact.confidence,
        source: "conversation",
      },
    });
    factIds.push(created.id);
  }

  // 3. Update RelationshipState: bump counters, update timestamp, append openThreads
  const existingState = await db.relationshipState.findUnique({
    where: { profileId: userProfileId },
  });
  const currentThreads = readJSON<string[]>(
    existingState?.openThreads ?? "[]",
    []
  );
  // Append new nextActions as open threads (dedupe, cap at 20)
  const mergedThreads = Array.from(
    new Set([...currentThreads, ...analysis.nextActions])
  ).slice(0, 20);
  const isPositive = analysis.sentiment === "positive";
  const now = new Date();
  if (existingState) {
    await db.relationshipState.update({
      where: { profileId: userProfileId },
      data: {
        totalInteractions: { increment: 1 },
        positiveInteractions: { increment: isPositive ? 1 : 0 },
        lastInteractionAt: now,
        openThreads: writeJSON(mergedThreads),
      },
    });
  } else {
    await db.relationshipState.create({
      data: {
        profileId: userProfileId,
        totalInteractions: 1,
        positiveInteractions: isPositive ? 1 : 0,
        lastInteractionAt: now,
        openThreads: writeJSON(mergedThreads),
      },
    });
  }

  // 4. Project-mention progress heuristic
  if (analysis.projectMentions.length > 0 && analysis.actionItems.length > 0) {
    const completionSignals = analysis.actionItems.filter((a) =>
      /\b(complete|done|finish|ship|deliver|merged?|resolved?)\b/i.test(a)
    );
    if (completionSignals.length > 0) {
      const lowerMentions = analysis.projectMentions.map((m) => m.toLowerCase());
      const projects = await db.project.findMany({
        where: { profileId, status: "active" },
        select: { id: true, name: true, progress: true },
      });
      for (const p of projects) {
        if (lowerMentions.some((m) => p.name.toLowerCase().includes(m) || m.includes(p.name.toLowerCase()))) {
          const newProgress = clamp(p.progress + 5, 0, 100);
          await updateProjectProgress(p.id, newProgress);
        }
      }
    }
  }

  // 5. Emit event
  await emit("info", "companion", "Conversation summarized", {
    summaryId: summary.id,
    topics: analysis.topics,
    factCount: factIds.length,
    sentiment: analysis.sentiment,
  });

  return { summaryId: summary.id, factIds };
}

// ─── 4. Personality Engine ──────────────────────────────────────────────────

const DEFAULT_TRAITS: Omit<CompanionTraitsDTO, "version" | "rationale"> = {
  curiosity: 0.7,
  confidence: 0.6,
  focus: 0.7,
  creativity: 0.65,
  empathy: 0.75,
  persistence: 0.7,
};

function toTraitsDTO(t: CompanionTraits): CompanionTraitsDTO {
  return {
    curiosity: t.curiosity,
    confidence: t.confidence,
    focus: t.focus,
    creativity: t.creativity,
    empathy: t.empathy,
    persistence: t.persistence,
    version: t.version,
    rationale: t.rationale,
  };
}

export async function getActiveTraits(): Promise<CompanionTraitsDTO> {
  const active = await db.companionTraits.findFirst({
    where: { isActive: true },
    orderBy: { version: "desc" },
  });
  if (active) return toTraitsDTO(active);

  // Seed initial trait vector on first boot.
  const seeded = await db.companionTraits.create({
    data: {
      version: 1,
      isActive: true,
      curiosity: DEFAULT_TRAITS.curiosity,
      confidence: DEFAULT_TRAITS.confidence,
      focus: DEFAULT_TRAITS.focus,
      creativity: DEFAULT_TRAITS.creativity,
      empathy: DEFAULT_TRAITS.empathy,
      persistence: DEFAULT_TRAITS.persistence,
      rationale: "Initial trait vector seeded on first access.",
    },
  });
  await emit("info", "companion", "Companion traits seeded", {
    version: 1,
  });
  return toTraitsDTO(seeded);
}

export async function evolveTraits(opts: {
  success?: boolean;
  failure?: boolean;
  reflection?: string;
  userSentiment?: "positive" | "neutral" | "negative";
}): Promise<CompanionTraitsDTO> {
  const current = await getActiveTraits();
  const currentRow = await db.companionTraits.findFirst({
    where: { isActive: true },
    orderBy: { version: "desc" },
  });
  if (!currentRow) {
    // Should not happen after getActiveTraits(), but guard anyway.
    return current;
  }

  const deltas: Record<string, number> = {
    curiosity: 0,
    confidence: 0,
    focus: 0,
    creativity: 0,
    empathy: 0,
    persistence: 0,
  };

  if (opts.success) {
    deltas.confidence += 0.02;
    deltas.persistence += 0.01;
    if (opts.userSentiment === "positive") {
      deltas.empathy += 0.005;
    }
  }
  if (opts.failure) {
    deltas.confidence -= 0.03;
    deltas.curiosity += 0.01;
    deltas.persistence += 0.005;
  }
  if (opts.reflection && opts.reflection.trim().length > 0) {
    deltas.creativity += 0.01;
    deltas.curiosity += 0.005;
  }
  if (opts.userSentiment === "negative") {
    deltas.empathy += 0.01;
  }

  const next = {
    curiosity: clamp01(round(current.curiosity + deltas.curiosity)),
    confidence: clamp01(round(current.confidence + deltas.confidence)),
    focus: clamp01(round(current.focus + deltas.focus)),
    creativity: clamp01(round(current.creativity + deltas.creativity)),
    empathy: clamp01(round(current.empathy + deltas.empathy)),
    persistence: clamp01(round(current.persistence + deltas.persistence)),
  };

  // Clamp confidence floor at 0.2 on failure (per spec).
  if (opts.failure && next.confidence < 0.2) {
    next.confidence = 0.2;
  }

  const rationaleParts: string[] = [];
  if (opts.success) rationaleParts.push("success");
  if (opts.failure) rationaleParts.push("failure");
  if (opts.reflection) rationaleParts.push("reflection");
  if (opts.userSentiment) rationaleParts.push(`userSentiment=${opts.userSentiment}`);
  const rationale = rationaleParts.length
    ? `Evolved from v${current.version} (${rationaleParts.join(", ")}).`
    : `Evolved from v${current.version}.`;

  // Deactivate old, create new versioned row (immutable history).
  await db.$transaction([
    db.companionTraits.update({
      where: { id: currentRow.id },
      data: { isActive: false },
    }),
    db.companionTraits.create({
      data: {
        version: current.version + 1,
        isActive: true,
        curiosity: next.curiosity,
        confidence: next.confidence,
        focus: next.focus,
        creativity: next.creativity,
        empathy: next.empathy,
        persistence: next.persistence,
        rationale,
      },
    }),
  ]);

  await emit("info", "companion", "Traits evolved", {
    from: current.version,
    to: current.version + 1,
    deltas,
  });

  return {
    ...next,
    version: current.version + 1,
    rationale,
  };
}

// ─── 5. Initiative Engine ──────────────────────────────────────────────────

const INITIATIVE_SYSTEM_PROMPT = `You are SUIKA's initiative engine. Given a set of signals (active goals, open blockers, pending/dead-lettered jobs, recently failed tasks, open threads), propose the MOST USEFUL actions SUIKA could take right now for the user. Output ONLY a STRICT JSON array — no markdown fences, no commentary.

Array element schema:
{
  "kind": "suggestion|autonomous_workflow|research_task|reminder",
  "title": "concise action title (max 80 chars)",
  "description": "what SUIKA would do (1-2 sentences)",
  "rationale": "why this is useful now, given the signals",
  "priority": 0-100,
  "linkedProjectId": null,
  "linkedGoalId": null
}

Rules:
- kind is one of the 4 enum values.
- "suggestion" = passive advice; "autonomous_workflow" = SUIKA runs a workflow; "research_task" = SUIKA gathers info; "reminder" = surface something the user may have forgotten.
- priority is 0..100 (higher = more urgent).
- linkedProjectId / linkedGoalId are null unless the signal explicitly references an id.
- Be concrete and specific. Each suggestion must be actionable within 24 hours.
- Limit to the top N suggestions by impact.`;

interface InitiativeSignals {
  goals: Array<{ id: string; title: string; status: string; progress: number }>;
  blockers: Array<{ id: string; title: string; projectId: string; severity: string }>;
  jobs: Array<{ id: string; title: string; status: string }>;
  failedTasks: Array<{ id: string; title: string }>;
  openThreads: string[];
}

export async function generateInitiatives(opts: {
  profileId?: string;
  maxSuggestions?: number;
}): Promise<InitiativeSuggestion[]> {
  const profileId = opts.profileId ?? DEFAULT_PROFILE_ID;
  const maxSuggestions = Math.max(1, Math.min(opts.maxSuggestions ?? 5, 20));

  // RelationshipState FKs to UserProfile.id — resolve once, may be null on a
  // fresh boot (no UserProfile row yet → no open threads, which is fine).
  const userProfileId = await findUserProfileId(profileId);

  // ── Gather signals ───────────────────────────────────────────────────────
  const [goals, blockers, jobs, failedTasks, relState] = await Promise.all([
    db.relationshipGoal.findMany({
      where: { profileId, status: "active" },
      select: { id: true, title: true, status: true, progress: true },
      take: 20,
    }),
    db.projectBlocker.findMany({
      where: { status: "open" },
      select: { id: true, title: true, projectId: true, severity: true },
      take: 20,
    }),
    db.executionJob.findMany({
      where: { status: { in: ["pending", "dead_lettered"] } },
      select: { id: true, title: true, status: true },
      take: 20,
    }),
    db.task.findMany({
      where: { status: "failed" },
      select: { id: true, title: true },
      orderBy: { createdAt: "desc" },
      take: 5,
    }),
    userProfileId
      ? db.relationshipState.findUnique({
          where: { profileId: userProfileId },
          select: { openThreads: true },
        })
      : Promise.resolve(null),
  ]);

  const signals: InitiativeSignals = {
    goals,
    blockers,
    jobs,
    failedTasks,
    openThreads: readJSON<string[]>(relState?.openThreads ?? "[]", []),
  };

  const totalSignals =
    signals.goals.length +
    signals.blockers.length +
    signals.jobs.length +
    signals.failedTasks.length +
    signals.openThreads.length;

  if (totalSignals === 0) {
    return [];
  }

  // ── LLM call ──────────────────────────────────────────────────────────────
  const prompt = `Signals:\n${JSON.stringify(signals, null, 2)}\n\nPropose up to ${maxSuggestions} initiative suggestions. Return ONLY a JSON array.`;
  const raw = await callLLM(INITIATIVE_SYSTEM_PROMPT, prompt);

  let suggestions: InitiativeSuggestion[] = [];
  const parsed = parseLLMJson<InitiativeSuggestion[] | { suggestions: InitiativeSuggestion[] }>(raw);
  if (Array.isArray(parsed)) {
    suggestions = parsed;
  } else if (parsed && Array.isArray((parsed as { suggestions?: InitiativeSuggestion[] }).suggestions)) {
    suggestions = (parsed as { suggestions: InitiativeSuggestion[] }).suggestions;
  }

  // ── Heuristic fallback ────────────────────────────────────────────────────
  if (suggestions.length === 0) {
    suggestions = heuristicInitiatives(signals, maxSuggestions);
  }

  // Normalize + bound
  suggestions = suggestions
    .filter((s) => s && typeof s.title === "string" && s.title.trim().length > 0)
    .slice(0, maxSuggestions)
    .map((s) => ({
      kind: normalizeInitiativeKind(s.kind),
      title: String(s.title).slice(0, 200),
      description: typeof s.description === "string" ? s.description.slice(0, 1000) : "",
      rationale: typeof s.rationale === "string" ? s.rationale.slice(0, 1000) : "",
      priority: clamp(Math.round(s.priority ?? 50), 0, 100),
      sourceSignals: {
        goalsCount: signals.goals.length,
        blockersCount: signals.blockers.length,
        jobsCount: signals.jobs.length,
        failedTasksCount: signals.failedTasks.length,
        openThreadsCount: signals.openThreads.length,
      },
      linkedProjectId: typeof s.linkedProjectId === "string" ? s.linkedProjectId : undefined,
      linkedGoalId: typeof s.linkedGoalId === "string" ? s.linkedGoalId : undefined,
    }));

  // ── Persist as InitiativeAction rows ──────────────────────────────────────
  const expiresAt = new Date(Date.now() + 24 * 60 * 60 * 1000);
  const persisted: InitiativeSuggestion[] = [];
  for (const s of suggestions) {
    const row = await db.initiativeAction.create({
      data: {
        kind: s.kind,
        title: s.title,
        description: s.description,
        rationale: s.rationale,
        priority: s.priority,
        status: "proposed",
        sourceSignals: writeJSON(s.sourceSignals),
        linkedProjectId: s.linkedProjectId ?? null,
        linkedGoalId: s.linkedGoalId ?? null,
        proposedAt: new Date(),
        expiresAt,
      },
    });
    persisted.push({ ...s, id: row.id });
  }

  await emit("info", "companion", `Initiative engine generated ${persisted.length} suggestions`, {
    count: persisted.length,
    signals: totalSignals,
  });

  return persisted;
}

function normalizeInitiativeKind(
  kind: string | undefined
): InitiativeSuggestion["kind"] {
  switch (kind) {
    case "suggestion":
    case "autonomous_workflow":
    case "research_task":
    case "reminder":
      return kind;
    default:
      return "suggestion";
  }
}

function heuristicInitiatives(
  signals: InitiativeSignals,
  max: number
): InitiativeSuggestion[] {
  const out: InitiativeSuggestion[] = [];
  const baseSignals = {
    goalsCount: signals.goals.length,
    blockersCount: signals.blockers.length,
    jobsCount: signals.jobs.length,
    failedTasksCount: signals.failedTasks.length,
    openThreadsCount: signals.openThreads.length,
  };

  if (signals.blockers.length > 0) {
    const b = signals.blockers[0];
    out.push({
      kind: "suggestion",
      title: `Draft mitigation for blocker: ${b.title}`,
      description: `Propose concrete steps to resolve the ${b.severity}-severity blocker on the active project.`,
      rationale: `${signals.blockers.length} open blocker(s) are blocking project progress.`,
      priority: 80,
      sourceSignals: baseSignals,
      linkedProjectId: b.projectId,
    });
  }

  for (const g of signals.goals.slice(0, 2)) {
    if (g.progress < 100) {
      out.push({
        kind: "suggestion",
        title: `Plan next milestone for: ${g.title}`,
        description: `Goal is at ${g.progress}%. Suggest the next milestone and the tasks required to reach it.`,
        rationale: `Active goal "${g.title}" is at ${g.progress}% — momentum check.`,
        priority: 60,
        sourceSignals: baseSignals,
        linkedGoalId: g.id,
      });
    }
  }

  if (signals.jobs.filter((j) => j.status === "dead_lettered").length > 0) {
    out.push({
      kind: "autonomous_workflow",
      title: "Retry dead-lettered jobs",
      description: "Re-enqueue jobs that exceeded their retry budget after a cooldown.",
      rationale: `${signals.jobs.filter((j) => j.status === "dead_lettered").length} job(s) are dead-lettered and may now succeed.`,
      priority: 50,
      sourceSignals: baseSignals,
    });
  }

  if (signals.failedTasks.length > 0) {
    out.push({
      kind: "research_task",
      title: "Diagnose recent task failures",
      description: "Investigate root cause of the most recent failed tasks and propose fixes.",
      rationale: `${signals.failedTasks.length} task(s) failed recently.`,
      priority: 55,
      sourceSignals: baseSignals,
    });
  }

  if (signals.openThreads.length > 0) {
    out.push({
      kind: "reminder",
      title: `Resume open thread: ${signals.openThreads[0].slice(0, 60)}`,
      description: "Surface the oldest unfinished discussion topic for the user to revisit.",
      rationale: `${signals.openThreads.length} open thread(s) in the relationship state.`,
      priority: 40,
      sourceSignals: baseSignals,
    });
  }

  return out.slice(0, max);
}

export async function listInitiatives(opts: {
  status?: string;
  limit?: number;
}): Promise<InitiativeAction[]> {
  return db.initiativeAction.findMany({
    where: opts.status ? { status: opts.status } : undefined,
    orderBy: { proposedAt: "desc" },
    take: Math.min(opts.limit ?? 50, 200),
  });
}

export async function decideInitiative(
  id: string,
  decision: "accept" | "reject"
): Promise<void> {
  const status = decision === "accept" ? "accepted" : "rejected";
  await db.initiativeAction.update({
    where: { id },
    data: { status, decidedAt: new Date() },
  });
  await emit("info", "companion", `Initiative ${status}`, {
    initiativeId: id,
    decision,
  });
}

export async function executeInitiative(
  id: string
): Promise<{ jobId?: string; error?: string }> {
  const initiative = await db.initiativeAction.findUnique({ where: { id } });
  if (!initiative) {
    return { error: "Initiative not found" };
  }
  if (initiative.status !== "accepted" && initiative.status !== "proposed") {
    return { error: `Initiative cannot be executed from status='${initiative.status}'` };
  }
  if (initiative.expiresAt && initiative.expiresAt.getTime() < Date.now()) {
    await db.initiativeAction.update({
      where: { id },
      data: { status: "expired" },
    });
    return { error: "Initiative has expired" };
  }

  // Non-dispatchable kinds just get marked executed.
  if (initiative.kind !== "autonomous_workflow" && initiative.kind !== "research_task") {
    await db.initiativeAction.update({
      where: { id },
      data: { status: "executed", executedAt: new Date() },
    });
    await emit("info", "companion", `Initiative executed (non-dispatchable): ${initiative.title}`, {
      initiativeId: id,
      kind: initiative.kind,
    });
    return {};
  }

  // Dispatchable kinds: create a root Task and enqueue a durable job.
  try {
    const suggestion: InitiativeSuggestion = {
      id: initiative.id,
      kind: initiative.kind as InitiativeSuggestion["kind"],
      title: initiative.title,
      description: initiative.description,
      rationale: initiative.rationale,
      priority: initiative.priority,
      sourceSignals: readJSON<Record<string, unknown>>(initiative.sourceSignals, {}),
      linkedProjectId: initiative.linkedProjectId ?? undefined,
      linkedGoalId: initiative.linkedGoalId ?? undefined,
    };

    const taskKind: TaskKind =
      initiative.kind === "research_task" ? "retrieve" : "reason";

    const rootTask = await db.task.create({
      data: {
        workspaceId: DEFAULT_WORKSPACE_ID,
        title: initiative.title,
        input: writeJSON({
          initiativeId: initiative.id,
          description: initiative.description,
          rationale: initiative.rationale,
          agentContext: companionAgentContext(suggestion),
        }),
        output: writeJSON({}),
        status: "pending",
        depth: 0,
        kind: taskKind,
      },
    });

    const agentContext = companionAgentContext(suggestion);
    const plan = {
      kinds: [taskKind] as TaskKind[],
      reasoning: `Companion-initiated ${initiative.kind}: ${initiative.title}`,
    };

    const job = await enqueue({
      taskId: rootTask.id,
      title: initiative.title,
      workspaceId: DEFAULT_WORKSPACE_ID,
      agentContext,
      plan,
    });

    await db.initiativeAction.update({
      where: { id },
      data: { status: "executed", executedAt: new Date() },
    });

    await emit("info", "companion", `Initiative dispatched: ${initiative.title}`, {
      initiativeId: id,
      jobId: job.id,
      taskId: rootTask.id,
    });

    return { jobId: job.id };
  } catch (e) {
    const msg = (e as Error)?.message ?? String(e);
    await emit("error", "companion", `Initiative execution failed: ${initiative.title}`, {
      initiativeId: id,
      error: msg.slice(0, 300),
    });
    return { error: msg };
  }
}

// ─── 6. Companion State Aggregator ──────────────────────────────────────────

export async function getCompanionState(opts: {
  profileId?: string;
}): Promise<CompanionState> {
  const profileId = opts.profileId ?? DEFAULT_PROFILE_ID;

  // UserProfile.profileId is the unique key (matches input); RelationshipState
  // FKs to UserProfile.id, so resolve it (find-only here; this is a read).
  const userProfileId = await findUserProfileId(profileId);

  const [
    userProfile,
    relProfile,
    relState,
    traits,
    activeProjects,
    openBlockers,
    initiativeCounts,
    recentDecisions,
    proposedInitiatives,
  ] = await Promise.all([
    db.userProfile.findUnique({ where: { profileId } }),
    db.relationshipProfile.findUnique({ where: { id: profileId } }),
    userProfileId
      ? db.relationshipState.findUnique({ where: { profileId: userProfileId } })
      : Promise.resolve(null),
    getActiveTraits(),
    db.project.findMany({
      where: { profileId, status: "active" },
      select: { id: true, progress: true },
    }),
    db.projectBlocker.count({ where: { status: "open" } }),
    db.initiativeAction.groupBy({
      by: ["status"],
      _count: true,
    }),
    db.projectDecision.findMany({
      orderBy: { decidedAt: "desc" },
      take: 5,
    }),
    db.initiativeAction.findMany({
      where: { status: "proposed", expiresAt: { gte: new Date() } },
      orderBy: { priority: "desc" },
      take: 5,
    }),
  ]);

  const name =
    userProfile?.preferredName ||
    relProfile?.name ||
    "User";
  const expertiseLevel = userProfile?.expertiseLevel ?? "generalist";

  const trustLevel = relState?.trustLevel ?? 0.5;
  const rapportLevel = relState?.rapportLevel ?? 0.5;
  const engagementTrend = relState?.engagementTrend ?? "stable";
  const totalInteractions = relState?.totalInteractions ?? 0;
  const openThreads = readJSON<string[]>(relState?.openThreads ?? "[]", []);

  const totalProgress = activeProjects.length > 0
    ? Math.round(
        activeProjects.reduce((s, p) => s + p.progress, 0) / activeProjects.length
      )
    : 0;

  const initiativeByStatus = (status: string): number =>
    initiativeCounts.find((c) => c.status === status)?._count ?? 0;

  const suggestedActions: InitiativeSuggestion[] = proposedInitiatives.map((i) => ({
    id: i.id,
    kind: normalizeInitiativeKind(i.kind),
    title: i.title,
    description: i.description,
    rationale: i.rationale,
    priority: i.priority,
    sourceSignals: readJSON<Record<string, unknown>>(i.sourceSignals, {}),
    linkedProjectId: i.linkedProjectId ?? undefined,
    linkedGoalId: i.linkedGoalId ?? undefined,
  }));

  return {
    profile: { name, preferredName: name, expertiseLevel },
    traits,
    relationship: {
      trustLevel,
      rapportLevel,
      engagementTrend,
      totalInteractions,
      openThreadsCount: openThreads.length,
    },
    projects: {
      active: activeProjects.length,
      totalProgress,
      openBlockers,
    },
    initiatives: {
      proposed: initiativeByStatus("proposed"),
      accepted: initiativeByStatus("accepted"),
      executed: initiativeByStatus("executed"),
    },
    recentDecisions,
    suggestedActions,
  };
}
